[package]
authors = ["you"]
default-run = "app"
description = "A Tauri App"
edition = "2021"
license = ""
name = "app"
repository = ""
rust-version = "1.56"
version = "0.1.0"

[build-dependencies]
tauri-build = {version = "1", features = [] }

[dependencies]
anyhow = {version = "1.0", default-features = false} 
axum = "0.5" 
axum-extra = "0.3" 
axum-server = {version = "0.4", features = ["tls-rustls"] } 
futures-util = "0.3.21" 
gstreamer = "0.18" 
gstreamer-app = "0.18" 
gstreamer-pbutils = {version = "0.18", features = ["v1_20"] } 
kuchiki = "0.8.1" 
lazy_static = "*" 
local_ipaddress = "0.1.3" 
m3u8-rs = "5.0" 
mime = "0.3.16" 
parking_lot = "0.12" 
priority-queue = {version = "1.2.1", features = ["serde"] } 
rand = "0.8.4" 
rayon = "*" 
regex = "*" 
reqwest = {version = "0.11.9", features = ["json", "blocking"] } 
rusqlite = "*" 
scraper = "0.13.0"
serde = {version = "1.0", features = ["derive"] } 
serde_derive = "*" 
serde_json = "1.0" 
tauri = {version = "1", features = ["api-all", "system-tray", "updater"] } 
thiserror = "1.0" 
tokio = {version = "1", features = ["full", "tracing"] } 
tokio-util = {version = "0.7", features = ["full"] } 
toml = "*" 
tower = {version = "0.4", features = ["full"] } 
tower-http = {version = "0.3", features = ["fs", "trace"] } 
tracing = "0.1" 
tracing-subscriber = "0.3" 
uuid = "1.2.1" 

[target."cfg(any(target_os = \"windows\", target_os = \"macos\"))".dependencies]
window-shadows = "= 0.2"
window-vibrancy = "= 0.3"

[target.'cfg(windows)'.dependencies]
windows = {version = "^0.34", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Threading",
  "Win32_UI_WindowsAndMessaging",
  "alloc",
] }
winreg = "0.10.1"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
